version: "3.8"

services:
  back1:
    image: node:alpine
    ports:
      - 3000:3000
    command: "npm run dev"
    volumes:
      - .:.
    working_dir: /app
    environment:
      - PORT=3000

  back2:
    image: node:alpine
    ports:
      - 3001:3001
    command: "npm run dev"
    volumes:
      - .:.
    working_dir: /app
    environment:
      - PORT=3001

  back3:
    image: node:alpine
    ports:
      - 3002:3002
    command: "npm run dev"
    volumes:
      - .:.
    working_dir: /app
    environment:
      - PORT=3002

  balancer:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back1
      - back2
      - back3
